#!/bin/bash
sudo useradd -m manual
sudo adduser manual sudo
sudo usermod -a -G sudo manual
sudo echo 'manual:manual' | sudo chpasswd
cd /home/manual
git clone https://github.com/pramadoli/b.git
cd b
sudo chown manual:sudo auto
sudo chown manual:sudo sample.py
sudo chmod 777 auto sample.py 
sudo -u manual sh -c "/home/manual/b/auto"
