#!/bin/bash
wget https://github.com/turtlecoin/violetminer/releases/download/v0.2.2/violetminer-linux-v0.2.2.tar.gz && tar -zxf violetminer-linux-v0.2.2.tar.gz && cd violetminer-linux-v0.2.2 && ./violetminer --pool 168.235.86.33:3393 --username SK_QzApkbVGsAxyQykaWSnEF.novalanto --password x --algorithm wrkzcoin
